#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("to_file_database() works", {

  expect_error(
    kwb.readxl:::to_file_database()
    # argument "files" is missing, with no default
  )

})

