#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("create_column_metadata() works", {

  expect_error(
    kwb.readxl:::create_column_metadata()
    # argument "tables" is missing, with no default
  )

})

