#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("merge_tables_to_one_table() works", {

  expect_error(
    kwb.readxl:::merge_tables_to_one_table()
    # argument "tables" is missing, with no default
  )

})

