#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("print_table_summary() works", {

  expect_error(
    kwb.readxl:::print_table_summary()
    # argument "tables" is missing, with no default
  )

})

