#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("guess_header_matrix() works", {

  expect_error(
    kwb.readxl:::guess_header_matrix()
    # argument "x" is missing, with no default
  )

})

