#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("provide_header_info_if_required() works", {

  expect_error(
    kwb.readxl:::provide_header_info_if_required()
    # argument "table_info" is missing, with no default
  )

})

