#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_sheet_info() works", {

  expect_error(
    kwb.readxl:::get_sheet_info()
    # argument "tables" is missing, with no default
  )

})

