#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("name_unnamed_tables() works", {

  expect_error(
    kwb.readxl:::name_unnamed_tables()
    # argument "table_info" is missing, with no default
  )

})

