#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("compact_column_info() works", {

  expect_error(
    kwb.readxl:::compact_column_info()
    # argument "column_info" is missing, with no default
  )

})

