#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("remove_empty_sheets() works", {

  expect_error(
    kwb.readxl:::remove_empty_sheets()
    # argument "text_sheets" is missing, with no default
  )

})

