#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("guess_column_type_from_type_matrix() works", {

  expect_error(
    kwb.readxl:::guess_column_type_from_type_matrix()
    # argument "type_matrix" is missing, with no default
  )

})

