#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("extend_table_info() works", {

  expect_error(
    kwb.readxl:::extend_table_info()
    # argument "tables" is missing, with no default
  )

})

