#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("print_logical_matrix() works", {

  expect_error(
    kwb.readxl:::print_logical_matrix()
    # argument "x" is missing, with no default
  )

})

