#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("extract_cell_regions() works", {

  expect_error(
    kwb.readxl:::extract_cell_regions()
    # argument "bounding_boxes" is missing, with no default
  )

})

