#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("add_hex_postfix() works", {

  expect_error(
    kwb.readxl:::add_hex_postfix()
    # argument "x" is missing, with no default
  )

})

