#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("text_matrix_to_numeric_matrix() works", {

  expect_error(
    kwb.readxl:::text_matrix_to_numeric_matrix()
    # argument "x" is missing, with no default
  )

})

