#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_type_matrix_from_text_matrix() works", {

  expect_error(
    kwb.readxl:::get_type_matrix_from_text_matrix()
    # argument "x" is missing, with no default
  )

})

