#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("bounding_boxes_to_table_info() works", {

  expect_error(
    kwb.readxl:::bounding_boxes_to_table_info()
    # argument "bounding_boxes" is missing, with no default
  )

})

