#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("to_folder_table() works", {

  expect_error(
    kwb.readxl:::to_folder_table()
    # argument "folder_paths" is missing, with no default
  )

})

