#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("debug_formatted() works", {

  expect_error(
    kwb.readxl:::debug_formatted()
    # argument "dbg" is missing, with no default
  )

})

