#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_combined_regions() works", {

  expect_error(
    kwb.readxl:::get_combined_regions()
    # argument "content" is missing, with no default
  )

})

