#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("guess_all_headers() works", {

  expect_error(
    kwb.readxl:::guess_all_headers()
    # argument "all_tables" is missing, with no default
  )

})

