#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("export_table_metadata() works", {

  expect_error(
    kwb.readxl:::export_table_metadata()
    # argument "table_info" is missing, with no default
  )

})

