#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("delete_empty_columns_right() works", {

  expect_error(
    kwb.readxl:::delete_empty_columns_right()
    # argument "x" is missing, with no default
  )

})

