#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("paste_path_parts() works", {

  expect_error(
    kwb.readxl:::paste_path_parts()
    # argument "path_parts" is missing, with no default
  )

})

