#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("seems_to_be_numeric() works", {

  expect_error(
    kwb.readxl:::seems_to_be_numeric()
    # argument "x" is missing, with no default
  )

})

