#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_named_regions_by_pattern() works", {

  expect_error(
    kwb.readxl:::get_named_regions_by_pattern()
    # argument "regions" is missing, with no default
  )

})

