#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("split_into_tables() works", {

  expect_error(
    kwb.readxl:::split_into_tables()
    # argument "text_sheet" is missing, with no default
  )

})

