#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_dim_frequencies() works", {

  expect_error(
    kwb.readxl:::get_dim_frequencies()
    # argument "tables" is missing, with no default
  )

})

