#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("header_matrix_to_column_info() works", {

  expect_error(
    kwb.readxl:::header_matrix_to_column_info()
    # argument "header_matrix" is missing, with no default
  )

})

