#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("guess_number_of_headers_from_text_matrix() works", {

  expect_error(
    kwb.readxl:::guess_number_of_headers_from_text_matrix()
    # argument "table_id" is missing, with no default
  )

})

