#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("name_even_tables_by_odd_tables() works", {

  expect_error(
    kwb.readxl:::name_even_tables_by_odd_tables()
    # argument "tables" is missing, with no default
  )

})

