#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("merge_table_infos() works", {

  expect_error(
    kwb.readxl:::merge_table_infos()
    # argument "table_infos" is missing, with no default
  )

})

