#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("update_table_info_with_header_info() works", {

  expect_error(
    kwb.readxl:::update_table_info_with_header_info()
    # argument "table_info" is missing, with no default
  )

})

