#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convert_text_matrix_list_to_data_frames() works", {

  expect_error(
    kwb.readxl:::convert_text_matrix_list_to_data_frames()
    # argument "all_tables" is missing, with no default
  )

})

