#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("to_sheet_table() works", {

  expect_error(
    kwb.readxl:::to_sheet_table()
    # argument "sheets" is missing, with no default
  )

})

