#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("looks_like_one_table() works", {

  expect_error(
    kwb.readxl:::looks_like_one_table()
    # argument "table_info" is missing, with no default
  )

})

