#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("looks_like_tables_with_captions() works", {

  expect_error(
    kwb.readxl:::looks_like_tables_with_captions()
    # argument "tables" is missing, with no default
  )

})

