#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("set_or_append() works", {

  expect_error(
    kwb.readxl:::set_or_append()
    # argument "x" is missing, with no default
  )

})

