#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("extract_tables_with_ranges() works", {

  expect_error(
    kwb.readxl:::extract_tables_with_ranges()
    # argument "table_info" is missing, with no default
  )

})

