#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("stop_formatted() works", {

  expect_error(
    kwb.readxl:::stop_formatted()
    # argument "fmt" is missing, with no default
  )

})

