#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("suggest_column_name() works", {

  expect_error(
    kwb.readxl:::suggest_column_name()
    # argument "column_info" is missing, with no default
  )

})

