#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("print_header_guesses() works", {

  expect_error(
    kwb.readxl:::print_header_guesses()
    # argument "text_matrices" is missing, with no default
  )

})

